env:
    MANIFEST: https://github.com/SuperiorOS/manifest.git -b eleven
    DEVICE: viva
    OEM: xiaomi
    LOCAL_MANIFEST: https://github.com/Raejend/local_manifest
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true        
    LUNCH_COMBO: superior_$DEVICE-user
    OUTPUT: A*.zip
    CLO: ci:ci
    CLO_1: 
    URI: 
    ROM_U: 1

task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
