env:
    MANIFEST: https://github.com/Havoc-OS/android_manifest.git -b thirteen --git-lfs
    DEVICE: fleur
    OEM: xiaomi
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt
    TARGET: bacon
    LUNCH_COMBO: octavi_${DEVICE}-userdebug
    OUTPUT: H*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[677d11880f7bd42349506045b163eec5a0ecbc93aa0c73c7e241e7b1dd39340f2e813cc02e057c8ab062051f0f9dff43]
    URI: https://sourceforge.net/projects/fleur/files/ccache/Octavi/ccache.tar.gz/download
    ROM_U: 0
 
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
