env:
    MANIFEST: https://github.com/Corvus-AOSP/android_manifest.git -b 13
    DEVICE: fleur
    OEM: xiaomi
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt
    TARGET: corvus
    LUNCH_COMBO: corvus_${DEVICE}-userdebug
    OUTPUT: C*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[65f39ad35028565d747a3510a29171d410643f879f1e587ecaf4530bf32b9602d1fd44a68316e0bdfa5260ecf1f584f6]
    URI: https://example.com
    ROM_U: 0
 
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
