env:
    MANIFEST:  https://github.com/Spark-Rom/manifest -b pyro
    DEVICE: fleur
    OEM: xiaomi
    LOCAL_MANIFEST: https://github.com/ShazuxD/local_manifestt
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true && export SELINUX_IGNORE_NEVERALLOWS=true
    EXTEA_CMD1: git clone https://github.com/ShazuxD/prebuilt_vendor_xiaomi_fleur du && cd du && bash *.sh ~/work/device/xiaomi/fleur/prebuilts
    LUNCH_COMBO: spark_${DEVICE}-userdebug
    OUTPUT: S*.zip
    CLO: idl:ci
    CLO_1: 
    URI: https://fleur.shazuxd7.workers.dev/0:/ci/ccache.tar.gz 
    ROM_U: 0
task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
