env:
    MANIFEST: https://github.com/Project-Elixir/manifest -b Tiramisu
    DEVICE: fleur
    OEM: xiaomi
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: aosp_$DEVICE-userdebug
    OUTPUT: P*.zip
    CLO: ci:ci
    CLO_1: ENCRYPTED[339bc560183187c0bcea8664283189d2f2d18d64c84d04f83268bc96578f120bb16d782221ff097160757b6f4f2fbfaf]
    URI: https://sourceforge.net/projects/fleur/files/ccache/Elixir/ccache.tar.gz/download
    ROM_U: 1

task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
