env:
    MANIFEST: https://github.com/Colt-Enigma/platform_manifest -b c13.1
    DEVICE: fleur
    OEM: xiaomi
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt
    TARGET: colt
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: colt_$DEVICE-userdebug
    OUTPUT: C*.zip
    CLO: 1:ci
    CLO_1: ENCRYPTED[3d6ae16d69e2cc6593dda8e2cf1fe1a3921ce4224b225573b898e456ae9bd5e557dc84aea50841f70f254c9cc6ea62c6]
    URI: https://sourceforge.net/projects/x01bd-asus/files/Extras/ccache.tar.gz/download
    ROM_U: 1
 
task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
