env:
    MANIFEST: https://github.com/PixelOS-AOSP/manifest.git -b thirteen
    DEVICE: fleur
    OEM: xiaomi
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: aosp_${DEVICE}-userdebug
    OUTPUT: P*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[ac1ab30f77234aa1e39a843f0ae7925d0949882f5aaeddeee2c83d797284c5573632da85284b40b7cca4e74564dc62bd]
    URI: https://sourceforge.net/projects/fleur/files/ccache/Pixelos/ccache.tar.gz/download
    ROM_U: 1
 
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 30G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
