env:
    MANIFEST: https://github.com/Colt-Enigma/platform_manifest -b c13.1
    DEVICE: fleur
    OEM: xiaomi
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt
    TARGET: colt
    EXTRA_CMD: export SKIP_ABI_CHECKS=true && export SELINUX_IGNORE_NEVERALLOWS=true
    EXTRA_CMD1: export WITH_GAPPS=true
    LUNCH_COMBO: colt_${DEVICE}-userdebug
    OUTPUT: C*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[d2dd0bb296948116fac1218dea0d7a3af1e2aacd2d151c8d15d4e4508b80ca3c0758ec94de1bfd411a1ae4b2f8517266]
    URI: https://sourceforge.net/projects/fleur/files/ccache/colt/ccache.tar.gz/download
    ROM_U: 1
task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
