env:
    MANIFEST: https://github.com/Evolution-X/manifest -b tiramisu-jem
    DEVICE: fleur
    OEM: xiaomi
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt
    TARGET: evolution 
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: evolution_$DEVICE-userdebug
    OUTPUT: e*.zip
    CLO: ci:ci
    CLO_1: ENCRYPTED[514fd104d86d8a6ccda83bcb5dea3169cc6135cd0de214a0bbff28d3c4f9a516491ead8b2ce89a716fbf861eb91a5b5b]
    URI: https://sourceforge.net/projects/fleur/files/ccache/EvoX/ccache.tar.gz/download
    ROM_U: 1

task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
