#!/bin/bash
cd ~/work
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 100G
ccache -o compression=true
ccache -z
sudo pip install gdown && cd device/xiaomi/viva && gdown https://drive.google.com/uc?id=1appK_U7WHo1PLada1V6OP2TIbor1vcIg
cd ~/work
. build/envsetup.sh
lunch "$LUNCH_COMBO"
mka $TARGET -j$(nproc --all) || curl -T /out/error.log temp.sh

